=== ReVamp-Electronics/revampwholesale/app/code/Aheadworks/Rma/etc/rma_custom_fields.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="custom_field" type="customField" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="customField">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="refers" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="visible_for_status_ids" type="statuses" minOccurs="1" maxOccurs="1"/>
            <xs:element name="editable_for_status_ids" type="statuses" minOccurs="1" maxOccurs="1"/>
            <xs:element name="editable_admin_for_status_ids" type="statuses" minOccurs="1" maxOccurs="1"/>
            <xs:element name="is_required" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            <xs:element name="is_display_in_label" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            <xs:element name="attribute" type="attribute" minOccurs="1" maxOccurs="1"/>
            <xs:element name="option" type="option" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="attribute">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="default" type="xs:integer" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="statuses">
        <xs:sequence>
            <xs:element name="id" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ReVamp-Electronics/revampwholesale/app/code/Aheadworks/Rma/etc/rma_custom_fields.xml
<?xml version="1.0"?>
<!--
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/
-->

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rma_custom_fields.xsd">
    <custom_field>
        <name>Resolution</name>
        <type>select</type>
        <refers>request</refers>
        <visible_for_status_ids>
            <id>all</id>
        </visible_for_status_ids>
        <editable_for_status_ids>
            <id>-1</id>
            <id>7</id>
        </editable_for_status_ids>
        <editable_admin_for_status_ids>
            <id>7</id>
        </editable_admin_for_status_ids>
        <is_required>1</is_required>
        <is_display_in_label>1</is_display_in_label>
        <attribute>
            <name>frontend_label</name>
            <value>Resolution</value>
        </attribute>
        <option>
            <value>Refund</value>
            <default>0</default>
        </option>
        <option>
            <value>Replacement</value>
            <default>0</default>
        </option>
    </custom_field>
    <custom_field>
        <name>Package Condition</name>
        <type>select</type>
        <refers>request</refers>
        <visible_for_status_ids>
            <id>all</id>
        </visible_for_status_ids>
        <editable_for_status_ids>
            <id>-1</id>
        </editable_for_status_ids>
        <editable_admin_for_status_ids>
            <id>none</id>
        </editable_admin_for_status_ids>
        <is_required>1</is_required>
        <is_display_in_label>1</is_display_in_label>
        <attribute>
            <name>frontend_label</name>
            <value>Package Condition</value>
        </attribute>
        <option>
            <value>Opened</value>
            <default>0</default>
        </option>
        <option>
            <value>Not opened</value>
            <default>0</default>
        </option>
        <option>
            <value>Damaged</value>
            <default>0</default>
        </option>
    </custom_field>
    <custom_field>
        <name>Reason</name>
        <type>select</type>
        <refers>item</refers>
        <visible_for_status_ids>
            <id>all</id>
        </visible_for_status_ids>
        <editable_for_status_ids>
            <id>-1</id>
        </editable_for_status_ids>
        <editable_admin_for_status_ids>
            <id>none</id>
        </editable_admin_for_status_ids>
        <is_required>1</is_required>
        <is_display_in_label>1</is_display_in_label>
        <attribute>
            <name>frontend_label</name>
            <value>Reason</value>
        </attribute>
        <option>
            <value>Wrong size</value>
            <default>0</default>
        </option>
        <option>
            <value>Wrong color</value>
            <default>0</default>
        </option>
        <option>
            <value>Don't like</value>
            <default>0</default>
        </option>
        <option>
            <value>I've changed my mind</value>
            <default>0</default>
        </option>
        <option>
            <value>Item broken</value>
            <default>0</default>
        </option>
    </custom_field>
</config>
